server:
  port: 9090
  servlet:
    context-path: /content/hub/api

## 环境配置
spring:
  main:
    allow-circular-references: true
  profiles:
    active: dev
  resources:
    cache:
      period: 0
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.javayh.content.hub.*
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: INPUT
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      #驼峰下划线转换
      column-underline: true
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
    aggressive-lazy-loading: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

secure:
  transmit:
    aes:
      key: 57b4a91281accee28f832baddea3c317
      iv: 2023110116
    type: aes
    enable: false
